### ISSUE TITLE
Integration of more methods? 

### ISSUE THREAD

**Issue by grst** [jdime/scRNAseq_cell_cluster_labeling#2]
Hi @jdime,

thank you very much for this benchmark. Automatically assigning cell types in single cell data is a great advance the processing pipeline and becomes more and more important as single cell datasets are being published at an increasing pace. 

In addition to the web-server/reference-based solutions you mentioned in the manuscript (Alavi et al., 2018; Alquicira-Hernandez et al., 2018; Crow et al., 2018), I recently came across several methods that run locally as an R/python package and do not need a reference besides marker genes:

* scVI cell type classification ([github](https://github.com/YosefLab/scVI), [biorxiv](https://www.biorxiv.org/content/biorxiv/early/2019/01/29/532895.full.pdf))
* SCINA ([github](https://github.com/jcao89757/SCINA))
* Garnett ([github](https://github.com/cole-trapnell-lab/garnett), [biorxiv](https://www.biorxiv.org/content/biorxiv/early/2019/02/25/538652.full.pdf))
* cellassign ([github](https://github.com/irrationone/cellassign), [biorxiv](https://www.biorxiv.org/content/biorxiv/early/2019/01/16/521914.full.pdf))

I was wondering if it would be possible for you to integrate them into your benchmark. Given that the methods are already available as a package it should be relatively straightforward and I believe it would greatly strengthen your work. 

Although these methods are new, they seem promising as they have been specifically developed for the task of single cell classification. I believe it would be highly interesting to see how they perform and how they compare to the more established tools you already consider in your benchmark. 

Best, 
Gregor 

CC @FFinotello

**Comment by jdime** [comment]
> * scVI cell type classification ([github](https://github.com/YosefLab/scVI), [biorxiv](https://www.biorxiv.org/content/biorxiv/early/2019/01/29/532895.full.pdf))
> * SCINA ([github](https://github.com/jcao89757/SCINA))
> * Garnett ([github](https://github.com/cole-trapnell-lab/garnett), [biorxiv](https://www.biorxiv.org/content/biorxiv/early/2019/02/25/538652.full.pdf))
> * cellassign ([github](https://github.com/irrationone/cellassign), [biorxiv](https://www.biorxiv.org/content/biorxiv/early/2019/01/16/521914.full.pdf))
> 
> I was wondering if it would be possible for you to integrate them into your benchmark. Given that the methods are already available as a package it should be relatively straightforward and I believe it would greatly strengthen your work.
> 
Hello Gregor. Thanks for your comment. I'll have a look and these methods you mentioned and a couple more suggested by Reviewers of our paper in F1000Research. Please keep an eye therein: https://f1000research.com/articles/8-296
