### ISSUE TITLE
How to generate input files for the main wrapper script.

### ISSUE THREAD

**Issue by bharati-mehani** [jdime/scRNAseq_cell_cluster_labeling#3]
Hi Javier,
Thank you for this benchmarking tool. I have already identified cell clusters in my dataset using cell ranger and Seurat and now willing to use your workflow. This could be a naive question, but I am really curious to ask how should I proceed to generate the needed input files for the main wrapper script directly from my Seurat object.

Is there any manual (which may be I am missing) that have already listed the order of commands or scripts to follow in-order to infer labels for my cell-clusters

Any help or suggestions will be highly appreciated.
Thanks.

**Comment by jdime** [comment]
Hello.

Sorry for the delay in my response. Are you trying to either:
(a) predict cell types in your scRNA-seq data, or
(b) do (a) AND benchmark tools

For (a) you need two inputs:
1) A matrix of genes (rows) and cell clusters (columns), with values being the average gene expression for each gene, for each cluster. From Seurat you can generate that matrix with function AverageExpression(). Then save it as a <tab> delimited file.
2) A list of cell type signatures in the so called *gmt format. This is one cell type per row with the cell type id in the first TWO fields, like this:

If you run in your console/terminal this one-line-command:
Rscript ~/path_to/obtains_GSVA_form_MatrixColumns.R -h
You'll get the help for that script, including a description of the inputs.

If you want to run (b) you'll need one file more. Let me know.
