### ISSUE TITLE
Single Cell Label Cluster

### ISSUE THREAD

**Issue by shatakshee1** [jdime/scRNAseq_cell_cluster_labeling#5]
I am trying to use CIBERSORT method for cell type labeling from your publication "Evaluation of methods to assign cell type labels to cell clusters from single-cell RNA-sequencing data".

    It would be very helpful if you could kindly clarify my following queries:

    1) Can we use the Ě xy and gene signature files in the web application of CIBERSORTX ?
Yes. Use them as "Mixture" infiles.
 
    2) In the file pbmc_22_10x_E_xy_matrix.tsv, I find the matrix contains information for 17786 genes. Therefore am I correct in assuming that this matrix contains all genes and not just differentially expressed marker genes?

Correct.
 
    3) Can we use a gene signature from one Single Cell experiment to label the clusters obtained from another Single Cell Experiment?
    If yes, then can we use the cluster annotated average expression matrix  of this second single cell experiment?

Yes, that's basically what we did to evaluate the PBMC datasets in our publication. We used Cibersort's LM22 matrix as "training" cell type profiles to predict cell types in each of the pbmc*_E_xy_* matrices.

**Comment by jdime** [comment]
Thanks @shatakshee1 for providing the answers I gave elsewhere.
Others interested in the topic, see above.
J.
